name: "Install flox"
description: "Installs flox on GitHub Actions for the supported platforms: GNU/Linux and macOS."
author: "flox <hello@floxdev.com>"

branding:
  color: "blue"
  icon: "moon"

inputs:

  base-url:
    description: "Download base URL of flox installer"
    default: "https://downloads.flox.dev/by-env/stable"

runs:
  using: 'node20'
  main: 'dist/index.js'
