name: "Install flox"
description: "Installs flox on GitHub Actions for the supported platforms: GNU/Linux and macOS."
author: "flox <hello@floxdev.com>"

branding:
  color: "blue"
  icon: "moon"

inputs:

  version:
    description: "Select a specific version from a channel."
    default: ""

  channel:
    description: "One of the following: stable, qa, nightly or specify a commit."
    default: "stable"

  base-url:
    deprecationMessage: "Please use channel option"
    description: "Download base URL of flox installer"
    default: ""

runs:
  using: 'node20'
  main: 'dist/index.js'
