schema-version = "1.10.0"

[install]
nodejs.pkg-path = "nodejs"
nodejs.version = "24"

[vars]

[hook]

[profile]

[services]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
