name: Apply label to new issues and PRs

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Add team  label automatically to new issues and PRs
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: "team-developer-support"


