name: "install-flox-action test"
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  simple-build:
    strategy:
      matrix:
        os: ["ubuntu-latest"] # macos not yet populated
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install flox"
        uses: "./"
        with:
          cache-key: "install-flox-action-test"

      - shell: "bash"
        run: "save-built"
