name: "install-flox-action test pre-release"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  install-flox-pre-release:
    strategy:
      matrix:
        os: ["ubuntu-latest"] # macos not yet populated
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install flox pre-release"
        uses: "./"
        with:
          cache-key: "install-flox-action-test"
          flox-installable-uri: "github:flox/floxpkgs#flox-prerelease.fromCatalog"
