name: "install-flox-action test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  simple-build:
    strategy:
      matrix:
        os: ["ubuntu-latest"] # macos not yet populated
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install flox"
        uses: "./"
        with:
          cache-key: "install-flox-action-test"

      - shell: "bash"
        run: "save-built"

  simple-cache-test:
    name: simple-build ${{ matrix.package }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - package: nixpkgs#hello
          - package: nixpkgs#jq

    steps:
      - name: Install flox
        uses: flox/install-flox-action@main
        with:
          substituter: "file://${{ runner.temp }}/nixcache"
          substituter-options: ""
          # NOTE: This should be coming from the secrets conext.
          # We're using the testing-only key here for testing purposes only!
          # See for https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context more info.
          substituter-key: "testing-only:77peiBuSA5nrF81iUqmWef67KajfGpzqcqPOIfz/qyrJQMaV5w7xdt8VCKrThI7Eu0T94shSuAj1ferF78bpww=="

      - name: Build
        run: |
          flox nix build --json -L --print-out-paths ${{ matrix.package }}
          rm result*

      - name: Cache
        run: |
          sudo rm -rf ${{ runner.temp }}/nixcache
          flox nix copy --to "$FLOX_SUBSTITUTER" -vv ${{ matrix.package }}

      - name: Build with caching
        run: |
          flox nix store gc
          flox nix build -j0 --json -L --print-out-paths ${{ matrix.package }}
