name: "Update Flox Environment"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

env:
  FLOX_DISABLE_METRICS: "true"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

        with:
          fetch-depth: 0

      - name: "Install Flox"
        uses: flox/install-flox-action@f6002ed63e483f134001de7b4b45be891e00b09f # v2.5.1


      - name: "Update Flox Environment"
        run: flox update

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8

        with:
          token: ${{ secrets.MANAGED_FLOXBOT_GITHUB_ACCESS_TOKEN_REPO_SCOPE }}
          commit-message: "chore: update flox environment"
          title: "chore: update flox environment"
          body: |
            Automated update of Flox environment packages.

            Run `flox activate` to test the updated environment locally.
          branch: update-flox-env
          delete-branch: true
